// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frisbee.proto

package models

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Node cotains ID and address
type Node struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Node) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Node) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type Error struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

type ID struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{2}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type CheckStatusRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckStatusRequest) Reset()         { *m = CheckStatusRequest{} }
func (m *CheckStatusRequest) String() string { return proto.CompactTextString(m) }
func (*CheckStatusRequest) ProtoMessage()    {}
func (*CheckStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{3}
}

func (m *CheckStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckStatusRequest.Unmarshal(m, b)
}
func (m *CheckStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckStatusRequest.Marshal(b, m, deterministic)
}
func (m *CheckStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckStatusRequest.Merge(m, src)
}
func (m *CheckStatusRequest) XXX_Size() int {
	return xxx_messageInfo_CheckStatusRequest.Size(m)
}
func (m *CheckStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckStatusRequest proto.InternalMessageInfo

func (m *CheckStatusRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CheckStatusReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckStatusReply) Reset()         { *m = CheckStatusReply{} }
func (m *CheckStatusReply) String() string { return proto.CompactTextString(m) }
func (*CheckStatusReply) ProtoMessage()    {}
func (*CheckStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{4}
}

func (m *CheckStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckStatusReply.Unmarshal(m, b)
}
func (m *CheckStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckStatusReply.Marshal(b, m, deterministic)
}
func (m *CheckStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckStatusReply.Merge(m, src)
}
func (m *CheckStatusReply) XXX_Size() int {
	return xxx_messageInfo_CheckStatusReply.Size(m)
}
func (m *CheckStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckStatusReply proto.InternalMessageInfo

func (m *CheckStatusReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Node)(nil), "models.Node")
	proto.RegisterType((*Error)(nil), "models.Error")
	proto.RegisterType((*ID)(nil), "models.ID")
	proto.RegisterType((*CheckStatusRequest)(nil), "models.CheckStatusRequest")
	proto.RegisterType((*CheckStatusReply)(nil), "models.CheckStatusReply")
}

func init() {
	proto.RegisterFile("frisbee.proto", fileDescriptor_ede8bc4112172419)
}

var fileDescriptor_ede8bc4112172419 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0x4d, 0xac, 0x2d, 0x3b, 0xb8, 0x22, 0x83, 0x48, 0xd8, 0x53, 0xc9, 0xa9, 0x78, 0xc8,
	0x41, 0xef, 0x7b, 0xf1, 0x03, 0xf6, 0x22, 0x12, 0x7f, 0x41, 0xd7, 0x8c, 0x35, 0xd8, 0x9a, 0x98,
	0xa4, 0x87, 0xfe, 0x7b, 0x31, 0xad, 0x07, 0x75, 0x6f, 0xef, 0x93, 0x3c, 0xcc, 0xf0, 0x0e, 0xac,
	0x5f, 0x83, 0x8d, 0x7b, 0x22, 0xe5, 0x83, 0x4b, 0x0e, 0xcb, 0xc1, 0x19, 0xea, 0xa3, 0xdc, 0x42,
	0xf1, 0xe8, 0x0c, 0xe1, 0x19, 0x70, 0x6b, 0x04, 0xab, 0x59, 0x73, 0xaa, 0xb9, 0x35, 0x88, 0x50,
	0x78, 0x17, 0x92, 0xe0, 0x35, 0x6b, 0xd6, 0x3a, 0xe7, 0xef, 0xb7, 0xd6, 0x98, 0x20, 0x8e, 0x6b,
	0xd6, 0xac, 0x74, 0xce, 0xb2, 0x82, 0x93, 0xfb, 0x10, 0x5c, 0x90, 0x17, 0xc0, 0x77, 0x77, 0x7f,
	0xc7, 0x48, 0x05, 0x78, 0xfb, 0x46, 0x2f, 0xef, 0xcf, 0xa9, 0x4d, 0x63, 0xd4, 0xf4, 0x39, 0x52,
	0x4c, 0x28, 0xa0, 0x1a, 0x28, 0xc6, 0xb6, 0xa3, 0xac, 0xae, 0xf4, 0x0f, 0xca, 0x2b, 0x38, 0xff,
	0xe5, 0xfb, 0x7e, 0xc2, 0x4b, 0x28, 0x63, 0xc6, 0x45, 0x5e, 0xe8, 0x7a, 0x07, 0xd5, 0xc3, 0xdc,
	0x09, 0xb7, 0x50, 0x3c, 0xd9, 0x8f, 0x0e, 0x37, 0x6a, 0xae, 0xa5, 0xfe, 0x2f, 0xdd, 0x88, 0x83,
	0x7f, 0xbe, 0x9f, 0xe4, 0xd1, 0xbe, 0xcc, 0x47, 0xb9, 0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x0d,
	0x91, 0xc3, 0x0a, 0x25, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FrisbeeClient is the client API for Frisbee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FrisbeeClient interface {
	Ping(ctx context.Context, in *CheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusReply, error)
}

type frisbeeClient struct {
	cc grpc.ClientConnInterface
}

func NewFrisbeeClient(cc grpc.ClientConnInterface) FrisbeeClient {
	return &frisbeeClient{cc}
}

func (c *frisbeeClient) Ping(ctx context.Context, in *CheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusReply, error) {
	out := new(CheckStatusReply)
	err := c.cc.Invoke(ctx, "/models.Frisbee/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrisbeeServer is the server API for Frisbee service.
type FrisbeeServer interface {
	Ping(context.Context, *CheckStatusRequest) (*CheckStatusReply, error)
}

// UnimplementedFrisbeeServer can be embedded to have forward compatible implementations.
type UnimplementedFrisbeeServer struct {
}

func (*UnimplementedFrisbeeServer) Ping(ctx context.Context, req *CheckStatusRequest) (*CheckStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterFrisbeeServer(s *grpc.Server, srv FrisbeeServer) {
	s.RegisterService(&_Frisbee_serviceDesc, srv)
}

func _Frisbee_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrisbeeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Frisbee/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrisbeeServer).Ping(ctx, req.(*CheckStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Frisbee_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.Frisbee",
	HandlerType: (*FrisbeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Frisbee_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frisbee.proto",
}
