// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frisbee.proto

package models

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Node cotains ID and address
type Node struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Node) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Node) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FindValueRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id                   []byte   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindValueRequest) Reset()         { *m = FindValueRequest{} }
func (m *FindValueRequest) String() string { return proto.CompactTextString(m) }
func (*FindValueRequest) ProtoMessage()    {}
func (*FindValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{2}
}

func (m *FindValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindValueRequest.Unmarshal(m, b)
}
func (m *FindValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindValueRequest.Marshal(b, m, deterministic)
}
func (m *FindValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindValueRequest.Merge(m, src)
}
func (m *FindValueRequest) XXX_Size() int {
	return xxx_messageInfo_FindValueRequest.Size(m)
}
func (m *FindValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindValueRequest proto.InternalMessageInfo

func (m *FindValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *FindValueRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type FindValueReply struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Nodes                []*Node  `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindValueReply) Reset()         { *m = FindValueReply{} }
func (m *FindValueReply) String() string { return proto.CompactTextString(m) }
func (*FindValueReply) ProtoMessage()    {}
func (*FindValueReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{3}
}

func (m *FindValueReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindValueReply.Unmarshal(m, b)
}
func (m *FindValueReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindValueReply.Marshal(b, m, deterministic)
}
func (m *FindValueReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindValueReply.Merge(m, src)
}
func (m *FindValueReply) XXX_Size() int {
	return xxx_messageInfo_FindValueReply.Size(m)
}
func (m *FindValueReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FindValueReply.DiscardUnknown(m)
}

var xxx_messageInfo_FindValueReply proto.InternalMessageInfo

func (m *FindValueReply) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *FindValueReply) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type FindValueProxyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindValueProxyRequest) Reset()         { *m = FindValueProxyRequest{} }
func (m *FindValueProxyRequest) String() string { return proto.CompactTextString(m) }
func (*FindValueProxyRequest) ProtoMessage()    {}
func (*FindValueProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{4}
}

func (m *FindValueProxyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindValueProxyRequest.Unmarshal(m, b)
}
func (m *FindValueProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindValueProxyRequest.Marshal(b, m, deterministic)
}
func (m *FindValueProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindValueProxyRequest.Merge(m, src)
}
func (m *FindValueProxyRequest) XXX_Size() int {
	return xxx_messageInfo_FindValueProxyRequest.Size(m)
}
func (m *FindValueProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindValueProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindValueProxyRequest proto.InternalMessageInfo

func (m *FindValueProxyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type FindValueProxyReply struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindValueProxyReply) Reset()         { *m = FindValueProxyReply{} }
func (m *FindValueProxyReply) String() string { return proto.CompactTextString(m) }
func (*FindValueProxyReply) ProtoMessage()    {}
func (*FindValueProxyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{5}
}

func (m *FindValueProxyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindValueProxyReply.Unmarshal(m, b)
}
func (m *FindValueProxyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindValueProxyReply.Marshal(b, m, deterministic)
}
func (m *FindValueProxyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindValueProxyReply.Merge(m, src)
}
func (m *FindValueProxyReply) XXX_Size() int {
	return xxx_messageInfo_FindValueProxyReply.Size(m)
}
func (m *FindValueProxyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FindValueProxyReply.DiscardUnknown(m)
}

var xxx_messageInfo_FindValueProxyReply proto.InternalMessageInfo

func (m *FindValueProxyReply) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type StoreProxyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreProxyRequest) Reset()         { *m = StoreProxyRequest{} }
func (m *StoreProxyRequest) String() string { return proto.CompactTextString(m) }
func (*StoreProxyRequest) ProtoMessage()    {}
func (*StoreProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{6}
}

func (m *StoreProxyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreProxyRequest.Unmarshal(m, b)
}
func (m *StoreProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreProxyRequest.Marshal(b, m, deterministic)
}
func (m *StoreProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreProxyRequest.Merge(m, src)
}
func (m *StoreProxyRequest) XXX_Size() int {
	return xxx_messageInfo_StoreProxyRequest.Size(m)
}
func (m *StoreProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreProxyRequest proto.InternalMessageInfo

func (m *StoreProxyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StoreProxyRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type FindNodeRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindNodeRequest) Reset()         { *m = FindNodeRequest{} }
func (m *FindNodeRequest) String() string { return proto.CompactTextString(m) }
func (*FindNodeRequest) ProtoMessage()    {}
func (*FindNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{7}
}

func (m *FindNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindNodeRequest.Unmarshal(m, b)
}
func (m *FindNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindNodeRequest.Marshal(b, m, deterministic)
}
func (m *FindNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindNodeRequest.Merge(m, src)
}
func (m *FindNodeRequest) XXX_Size() int {
	return xxx_messageInfo_FindNodeRequest.Size(m)
}
func (m *FindNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindNodeRequest proto.InternalMessageInfo

func (m *FindNodeRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type FindNodeReply struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindNodeReply) Reset()         { *m = FindNodeReply{} }
func (m *FindNodeReply) String() string { return proto.CompactTextString(m) }
func (*FindNodeReply) ProtoMessage()    {}
func (*FindNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{8}
}

func (m *FindNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindNodeReply.Unmarshal(m, b)
}
func (m *FindNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindNodeReply.Marshal(b, m, deterministic)
}
func (m *FindNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindNodeReply.Merge(m, src)
}
func (m *FindNodeReply) XXX_Size() int {
	return xxx_messageInfo_FindNodeReply.Size(m)
}
func (m *FindNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FindNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_FindNodeReply proto.InternalMessageInfo

func (m *FindNodeReply) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type ID struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{9}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type PingRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Origin               *Node    `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{10}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PingRequest) GetOrigin() *Node {
	if m != nil {
		return m.Origin
	}
	return nil
}

type PingReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Recipient            *Node    `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{11}
}

func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (m *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(m, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

func (m *PingReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PingReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *PingReply) GetRecipient() *Node {
	if m != nil {
		return m.Recipient
	}
	return nil
}

type ProbeRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeRequest) Reset()         { *m = ProbeRequest{} }
func (m *ProbeRequest) String() string { return proto.CompactTextString(m) }
func (*ProbeRequest) ProtoMessage()    {}
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{12}
}

func (m *ProbeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeRequest.Unmarshal(m, b)
}
func (m *ProbeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeRequest.Marshal(b, m, deterministic)
}
func (m *ProbeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeRequest.Merge(m, src)
}
func (m *ProbeRequest) XXX_Size() int {
	return xxx_messageInfo_ProbeRequest.Size(m)
}
func (m *ProbeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeRequest proto.InternalMessageInfo

func (m *ProbeRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ProbeReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeReply) Reset()         { *m = ProbeReply{} }
func (m *ProbeReply) String() string { return proto.CompactTextString(m) }
func (*ProbeReply) ProtoMessage()    {}
func (*ProbeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{13}
}

func (m *ProbeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeReply.Unmarshal(m, b)
}
func (m *ProbeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeReply.Marshal(b, m, deterministic)
}
func (m *ProbeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeReply.Merge(m, src)
}
func (m *ProbeReply) XXX_Size() int {
	return xxx_messageInfo_ProbeReply.Size(m)
}
func (m *ProbeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeReply proto.InternalMessageInfo

func (m *ProbeReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type StoreRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreRequest) Reset()         { *m = StoreRequest{} }
func (m *StoreRequest) String() string { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()    {}
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede8bc4112172419, []int{14}
}

func (m *StoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreRequest.Unmarshal(m, b)
}
func (m *StoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreRequest.Marshal(b, m, deterministic)
}
func (m *StoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreRequest.Merge(m, src)
}
func (m *StoreRequest) XXX_Size() int {
	return xxx_messageInfo_StoreRequest.Size(m)
}
func (m *StoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreRequest proto.InternalMessageInfo

func (m *StoreRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StoreRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "models.Node")
	proto.RegisterType((*Error)(nil), "models.Error")
	proto.RegisterType((*FindValueRequest)(nil), "models.FindValueRequest")
	proto.RegisterType((*FindValueReply)(nil), "models.FindValueReply")
	proto.RegisterType((*FindValueProxyRequest)(nil), "models.FindValueProxyRequest")
	proto.RegisterType((*FindValueProxyReply)(nil), "models.FindValueProxyReply")
	proto.RegisterType((*StoreProxyRequest)(nil), "models.StoreProxyRequest")
	proto.RegisterType((*FindNodeRequest)(nil), "models.FindNodeRequest")
	proto.RegisterType((*FindNodeReply)(nil), "models.FindNodeReply")
	proto.RegisterType((*ID)(nil), "models.ID")
	proto.RegisterType((*PingRequest)(nil), "models.PingRequest")
	proto.RegisterType((*PingReply)(nil), "models.PingReply")
	proto.RegisterType((*ProbeRequest)(nil), "models.ProbeRequest")
	proto.RegisterType((*ProbeReply)(nil), "models.ProbeReply")
	proto.RegisterType((*StoreRequest)(nil), "models.StoreRequest")
}

func init() {
	proto.RegisterFile("frisbee.proto", fileDescriptor_ede8bc4112172419)
}

var fileDescriptor_ede8bc4112172419 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xad, 0xed, 0x38, 0xe0, 0xdb, 0xa4, 0x8f, 0xdb, 0xb4, 0x18, 0x23, 0xa4, 0x74, 0xe8, 0xc2,
	0x80, 0x14, 0xa1, 0x86, 0x05, 0x42, 0x88, 0x6e, 0xa0, 0x12, 0x0b, 0xaa, 0xc8, 0x48, 0xec, 0x93,
	0x78, 0x88, 0x2c, 0x5c, 0x8f, 0x19, 0x3b, 0x88, 0x7c, 0x16, 0x7f, 0x88, 0xe6, 0x95, 0x8c, 0x9d,
	0x86, 0x4a, 0xdd, 0x79, 0xe6, 0xdc, 0x39, 0xe7, 0xdc, 0x97, 0xa1, 0xff, 0x83, 0x67, 0xd5, 0x8c,
	0xd2, 0x51, 0xc9, 0x59, 0xcd, 0xb0, 0x7b, 0xcb, 0x52, 0x9a, 0x57, 0xe4, 0x23, 0x74, 0x6e, 0x58,
	0x4a, 0xf1, 0x00, 0xdc, 0x2c, 0x0d, 0x9d, 0xa1, 0x13, 0xf7, 0x12, 0x37, 0x4b, 0x11, 0xa1, 0x53,
	0x32, 0x5e, 0x87, 0xee, 0xd0, 0x89, 0xfb, 0x89, 0xfc, 0x16, 0x77, 0xd3, 0x34, 0xe5, 0xa1, 0x37,
	0x74, 0xe2, 0x20, 0x91, 0xdf, 0xe4, 0x1c, 0xfc, 0xcf, 0x9c, 0x33, 0x8e, 0x21, 0x3c, 0xba, 0xa5,
	0x55, 0x35, 0x5d, 0x50, 0xc9, 0x12, 0x24, 0xe6, 0x48, 0xde, 0xc2, 0xd1, 0x75, 0x56, 0xa4, 0xdf,
	0xa7, 0xf9, 0x92, 0x26, 0xf4, 0xd7, 0x92, 0x56, 0x35, 0x1e, 0x81, 0xf7, 0x93, 0xae, 0x74, 0xa4,
	0xf8, 0xd4, 0x06, 0x5c, 0x63, 0x80, 0xdc, 0xc0, 0x81, 0xf5, 0xaa, 0xcc, 0x57, 0x42, 0x61, 0xce,
	0x8a, 0x9a, 0x16, 0xb5, 0xf6, 0x69, 0x8e, 0x48, 0xc0, 0x2f, 0x58, 0x4a, 0xab, 0xd0, 0x1d, 0x7a,
	0xf1, 0xfe, 0x65, 0x6f, 0xa4, 0x92, 0x1b, 0x89, 0xcc, 0x12, 0x05, 0x91, 0x97, 0x70, 0xba, 0xe6,
	0x9b, 0x70, 0xf6, 0x67, 0xb5, 0xd3, 0x0a, 0x79, 0x0d, 0x27, 0xed, 0x50, 0xa1, 0x3f, 0x00, 0xff,
	0xb7, 0xb8, 0xd2, 0xea, 0xea, 0x40, 0xae, 0xe0, 0xf8, 0x5b, 0xcd, 0xf8, 0x3d, 0x9c, 0xb6, 0x79,
	0xb7, 0x61, 0x9e, 0x9c, 0xc3, 0xa1, 0x50, 0x93, 0x5e, 0xf5, 0xf3, 0x56, 0x33, 0xc8, 0x18, 0xfa,
	0x9b, 0x10, 0x61, 0x65, 0x9d, 0xb0, 0xb3, 0x3b, 0xe1, 0x01, 0xb8, 0x5f, 0x3e, 0x6d, 0x51, 0x7d,
	0x85, 0xfd, 0x49, 0x56, 0x2c, 0x8c, 0xd2, 0xce, 0xae, 0xe1, 0x05, 0x74, 0x19, 0xcf, 0x16, 0x59,
	0x21, 0xfd, 0xb6, 0x35, 0x34, 0x46, 0x6a, 0x08, 0x14, 0x9d, 0x70, 0x75, 0x06, 0xdd, 0xaa, 0x9e,
	0xd6, 0xcb, 0x4a, 0x73, 0xe9, 0x13, 0xbe, 0x00, 0x9f, 0x8a, 0x19, 0xd1, 0x4c, 0x7d, 0xc3, 0x24,
	0x07, 0x27, 0x51, 0x18, 0xbe, 0x82, 0x80, 0xd3, 0x79, 0x56, 0x66, 0xa2, 0x44, 0xde, 0x1d, 0x92,
	0x1b, 0x98, 0xc4, 0xd0, 0x9b, 0x70, 0x36, 0xa3, 0xf7, 0x66, 0x41, 0x2e, 0x00, 0x74, 0xe4, 0x7f,
	0x0c, 0x92, 0xf7, 0xd0, 0x93, 0x3d, 0x7c, 0x40, 0xfb, 0x2e, 0xff, 0x7a, 0x70, 0x78, 0xad, 0x56,
	0x6b, 0x22, 0x36, 0x6b, 0xce, 0x72, 0x7c, 0x03, 0x1d, 0x51, 0x15, 0x3c, 0x31, 0x09, 0x58, 0x25,
	0x8f, 0x8e, 0x9b, 0x97, 0x65, 0xbe, 0x22, 0x7b, 0x38, 0x02, 0x5f, 0x3a, 0xc0, 0x81, 0x41, 0x6d,
	0x43, 0x51, 0xb3, 0x64, 0x64, 0x0f, 0x3f, 0xc0, 0x63, 0x33, 0x11, 0xf8, 0xc4, 0x80, 0xad, 0x31,
	0x8a, 0x4e, 0xb7, 0x01, 0xa5, 0x76, 0x05, 0xc1, 0x7a, 0xc0, 0x31, 0xb4, 0xa3, 0xec, 0x25, 0x8d,
	0xce, 0xee, 0x40, 0x14, 0xc1, 0x18, 0x7c, 0x59, 0xd6, 0x8d, 0x5d, 0xbb, 0x1f, 0x11, 0xb6, 0x6e,
	0xd5, 0x23, 0x7b, 0xa3, 0xe5, 0xb6, 0xe0, 0xf3, 0x2d, 0x01, 0x7b, 0x8b, 0xa2, 0x67, 0xbb, 0x60,
	0xc5, 0xf7, 0x0e, 0x60, 0xb3, 0x79, 0xf8, 0xb4, 0x51, 0xb8, 0x06, 0x4f, 0xbb, 0x7a, 0xb3, 0xae,
	0xfc, 0x07, 0x8e, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xcc, 0x06, 0xfc, 0x14, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FrisbeeProtocolClient is the client API for FrisbeeProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FrisbeeProtocolClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*Error, error)
	FindNode(ctx context.Context, in *FindNodeRequest, opts ...grpc.CallOption) (*FindNodeReply, error)
	FindValue(ctx context.Context, in *FindValueRequest, opts ...grpc.CallOption) (*FindValueReply, error)
	Probe(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeReply, error)
	FindValueProxy(ctx context.Context, in *FindValueProxyRequest, opts ...grpc.CallOption) (*FindValueProxyReply, error)
	StoreProxy(ctx context.Context, in *StoreProxyRequest, opts ...grpc.CallOption) (*Error, error)
}

type frisbeeProtocolClient struct {
	cc grpc.ClientConnInterface
}

func NewFrisbeeProtocolClient(cc grpc.ClientConnInterface) FrisbeeProtocolClient {
	return &frisbeeProtocolClient{cc}
}

func (c *frisbeeProtocolClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/models.FrisbeeProtocol/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frisbeeProtocolClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/models.FrisbeeProtocol/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frisbeeProtocolClient) FindNode(ctx context.Context, in *FindNodeRequest, opts ...grpc.CallOption) (*FindNodeReply, error) {
	out := new(FindNodeReply)
	err := c.cc.Invoke(ctx, "/models.FrisbeeProtocol/FindNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frisbeeProtocolClient) FindValue(ctx context.Context, in *FindValueRequest, opts ...grpc.CallOption) (*FindValueReply, error) {
	out := new(FindValueReply)
	err := c.cc.Invoke(ctx, "/models.FrisbeeProtocol/FindValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frisbeeProtocolClient) Probe(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeReply, error) {
	out := new(ProbeReply)
	err := c.cc.Invoke(ctx, "/models.FrisbeeProtocol/Probe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frisbeeProtocolClient) FindValueProxy(ctx context.Context, in *FindValueProxyRequest, opts ...grpc.CallOption) (*FindValueProxyReply, error) {
	out := new(FindValueProxyReply)
	err := c.cc.Invoke(ctx, "/models.FrisbeeProtocol/FindValueProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frisbeeProtocolClient) StoreProxy(ctx context.Context, in *StoreProxyRequest, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/models.FrisbeeProtocol/StoreProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrisbeeProtocolServer is the server API for FrisbeeProtocol service.
type FrisbeeProtocolServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	Store(context.Context, *StoreRequest) (*Error, error)
	FindNode(context.Context, *FindNodeRequest) (*FindNodeReply, error)
	FindValue(context.Context, *FindValueRequest) (*FindValueReply, error)
	Probe(context.Context, *ProbeRequest) (*ProbeReply, error)
	FindValueProxy(context.Context, *FindValueProxyRequest) (*FindValueProxyReply, error)
	StoreProxy(context.Context, *StoreProxyRequest) (*Error, error)
}

// UnimplementedFrisbeeProtocolServer can be embedded to have forward compatible implementations.
type UnimplementedFrisbeeProtocolServer struct {
}

func (*UnimplementedFrisbeeProtocolServer) Ping(ctx context.Context, req *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedFrisbeeProtocolServer) Store(ctx context.Context, req *StoreRequest) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedFrisbeeProtocolServer) FindNode(ctx context.Context, req *FindNodeRequest) (*FindNodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindNode not implemented")
}
func (*UnimplementedFrisbeeProtocolServer) FindValue(ctx context.Context, req *FindValueRequest) (*FindValueReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindValue not implemented")
}
func (*UnimplementedFrisbeeProtocolServer) Probe(ctx context.Context, req *ProbeRequest) (*ProbeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Probe not implemented")
}
func (*UnimplementedFrisbeeProtocolServer) FindValueProxy(ctx context.Context, req *FindValueProxyRequest) (*FindValueProxyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindValueProxy not implemented")
}
func (*UnimplementedFrisbeeProtocolServer) StoreProxy(ctx context.Context, req *StoreProxyRequest) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreProxy not implemented")
}

func RegisterFrisbeeProtocolServer(s *grpc.Server, srv FrisbeeProtocolServer) {
	s.RegisterService(&_FrisbeeProtocol_serviceDesc, srv)
}

func _FrisbeeProtocol_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrisbeeProtocolServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.FrisbeeProtocol/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrisbeeProtocolServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrisbeeProtocol_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrisbeeProtocolServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.FrisbeeProtocol/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrisbeeProtocolServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrisbeeProtocol_FindNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrisbeeProtocolServer).FindNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.FrisbeeProtocol/FindNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrisbeeProtocolServer).FindNode(ctx, req.(*FindNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrisbeeProtocol_FindValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrisbeeProtocolServer).FindValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.FrisbeeProtocol/FindValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrisbeeProtocolServer).FindValue(ctx, req.(*FindValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrisbeeProtocol_Probe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrisbeeProtocolServer).Probe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.FrisbeeProtocol/Probe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrisbeeProtocolServer).Probe(ctx, req.(*ProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrisbeeProtocol_FindValueProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindValueProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrisbeeProtocolServer).FindValueProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.FrisbeeProtocol/FindValueProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrisbeeProtocolServer).FindValueProxy(ctx, req.(*FindValueProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrisbeeProtocol_StoreProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrisbeeProtocolServer).StoreProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.FrisbeeProtocol/StoreProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrisbeeProtocolServer).StoreProxy(ctx, req.(*StoreProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FrisbeeProtocol_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.FrisbeeProtocol",
	HandlerType: (*FrisbeeProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _FrisbeeProtocol_Ping_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _FrisbeeProtocol_Store_Handler,
		},
		{
			MethodName: "FindNode",
			Handler:    _FrisbeeProtocol_FindNode_Handler,
		},
		{
			MethodName: "FindValue",
			Handler:    _FrisbeeProtocol_FindValue_Handler,
		},
		{
			MethodName: "Probe",
			Handler:    _FrisbeeProtocol_Probe_Handler,
		},
		{
			MethodName: "FindValueProxy",
			Handler:    _FrisbeeProtocol_FindValueProxy_Handler,
		},
		{
			MethodName: "StoreProxy",
			Handler:    _FrisbeeProtocol_StoreProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frisbee.proto",
}
